let data = {
  cards: [
    {
      id: 0,
      title: "Caranthir Ar-Feiniel",
      pictureDir: "/pictures/mo/caranthir.png",
      chosen: false,
    },
    {
      id: 1,
      title: "Detlaff: Higher Vampire",
      pictureDir: "/pictures/mo/detlaff.png",
      chosen: false,
    },
    {
      id: 2,
      title: "Haunt",
      pictureDir: "/pictures/mo/haunt.png",
      chosen: false,
    },
    {
      id: 3,
      title: "Keltullis",
      pictureDir: "/pictures/mo/keltullis.png",
      chosen: false,
    },
    {
      id: 4,
      title: "Kikimore Queen",
      pictureDir: "/pictures/mo/kikimore.png",
      chosen: false,
    },
    {
      id: 5,
      title: "Viy",
      pictureDir: "/pictures/mo/viy.png",
      chosen: false,
    },
    {
      id: 6,
      title: "Yghern",
      pictureDir: "/pictures/mo/yghern.png",
      chosen: false,
    },
    {
      id: 7,
      title: "Allgod",
      pictureDir: "/pictures/neutral/allgod.png",
      chosen: false,
    },
    {
      id: 8,
      title: "Ciri",
      pictureDir: "/pictures/neutral/ciri.png",
      chosen: false,
    },
    {
      id: 9,
      title: "Geralt of Rivia",
      pictureDir: "/pictures/neutral/geralt.png",
      chosen: false,
    },
    {
      id: 10,
      title: "Korathi Heatwave",
      pictureDir: "/pictures/neutral/heatwave.png",
      chosen: false,
    },
    {
      id: 11,
      title: "Shupe's Day Off",
      pictureDir: "/pictures/neutral/shupe.png",
      chosen: false,
    },
    {
      id: 12,
      title: "Triss Merigold",
      pictureDir: "/pictures/neutral/triss.png",
      chosen: false,
    },
    {
      id: 13,
      title: "Yennefer of Vengerberg",
      pictureDir: "/pictures/neutral/yennefer.png",
      chosen: false,
    },
    {
      id: 14,
      title: "Masquerade Ball",
      pictureDir: "/pictures/ng/ball.png",
      chosen: false,
    },
    {
      id: 15,
      title: "Cahir Dyffryn",
      pictureDir: "/pictures/ng/cahir.png",
      chosen: false,
    },
    {
      id: 16,
      title: "Damien de la Tour",
      pictureDir: "/pictures/ng/damien.png",
      chosen: false,
    },
    {
      id: 17,
      title: "Ivar Evil-Eye",
      pictureDir: "/pictures/ng/ivar.png",
      chosen: false,
    },
    {
      id: 18,
      title: "Ramon Tyrconnel",
      pictureDir: "/pictures/ng/ramon.png",
      chosen: false,
    },
    {
      id: 19,
      title: "Stefan Skellen",
      pictureDir: "/pictures/ng/stefan.png",
      chosen: false,
    },
    {
      id: 20,
      title: "Vincent van Moorlehelm",
      pictureDir: "/pictures/ng/vincent.png",
      chosen: false,
    },
    {
      id: 21,
      title: "Prince Anseis",
      pictureDir: "/pictures/nr/anseis.png",
      chosen: false,
    },
    {
      id: 22,
      title: "Amphibious Assault",
      pictureDir: "/pictures/nr/assault.png",
      chosen: false,
    },
    {
      id: 23,
      title: "Bloody Baron",
      pictureDir: "/pictures/nr/baron.png",
      chosen: false,
    },
    {
      id: 24,
      title: "Draug",
      pictureDir: "/pictures/nr/draug.png",
      chosen: false,
    },
    {
      id: 25,
      title: "Falibor",
      pictureDir: "/pictures/nr/falibor.png",
      chosen: false,
    },
    {
      id: 26,
      title: "Philippa: Blind Fury",
      pictureDir: "/pictures/nr/phillipa.png",
      chosen: false,
    },
    {
      id: 27,
      title: "Siege",
      pictureDir: "/pictures/nr/siege.png",
      chosen: false,
    },
    {
      id: 28,
      title: "Vysogota of Corvo",
      pictureDir: "/pictures/nr/vysogota.png",
      chosen: false,
    },
    {
      id: 29,
      title: "Arnaghad",
      pictureDir: "/pictures/sk/arna.png",
      chosen: false,
    },
    {
      id: 30,
      title: "Blood Eagle",
      pictureDir: "/pictures/sk/bloodeagle.png",
      chosen: false,
    },
    {
      id: 31,
      title: "Wild Boar of the Sea",
      pictureDir: "/pictures/sk/boar.png",
      chosen: false,
    },
    {
      id: 32,
      title: "Cerys an Craite",
      pictureDir: "/pictures/sk/cerys.png",
      chosen: false,
    },
    {
      id: 33,
      title: "Gedyneith",
      pictureDir: "/pictures/sk/gedy.png",
      chosen: false,
    },
    {
      id: 34,
      title: "Hemdall",
      pictureDir: "/pictures/sk/hemdall.png",
      chosen: false,
    },
    {
      id: 35,
      title: "Kambi",
      pictureDir: "/pictures/sk/kambi.png",
      chosen: false,
    },
    {
      id: 36,
      title: "Lippy",
      pictureDir: "/pictures/sk/lippy.png",
      chosen: false,
    },
    {
      id: 37,
      title: "Fauve",
      pictureDir: "/pictures/st/fauve.png",
      chosen: false,
    },
    {
      id: 38,
      title: "Feign Death",
      pictureDir: "/pictures/st/feigndeath.png",
      chosen: false,
    },
    {
      id: 39,
      title: "Gezras of Leyda",
      pictureDir: "/pictures/st/gezras.png",
      chosen: false,
    },
    {
      id: 40,
      title: "Novigradian Justice",
      pictureDir: "/pictures/st/justice.png",
      chosen: false,
    },
    {
      id: 41,
      title: "The Great Oak",
      pictureDir: "/pictures/st/oak.png",
      chosen: false,
    },
    {
      id: 42,
      title: "Forest Protector",
      pictureDir: "/pictures/st/protector.png",
      chosen: false,
    },
    {
      id: 43,
      title: "Schirru",
      pictureDir: "/pictures/st/schirru.png",
      chosen: false,
    },
    {
      id: 44,
      title: "Water of Brokilon",
      pictureDir: "/pictures/st/waters.png",
      chosen: false,
    },
    {
      id: 45,
      title: "Dies Irae",
      pictureDir: "/pictures/sy/dies.png",
      chosen: false,
    },
    {
      id: 46,
      title: "Madam Luiza",
      pictureDir: "/pictures/sy/luiza.png",
      chosen: false,
    },
    {
      id: 47,
      title: "Passiflora",
      pictureDir: "/pictures/sy/passi.png",
      chosen: false,
    },
    {
      id: 48,
      title: "Philippa Eilhart",
      pictureDir: "/pictures/sy/phillipa.png",
      chosen: false,
    },
    {
      id: 49,
      title: "Salamander",
      pictureDir: "/pictures/sy/salamander.png",
      chosen: false,
    },
    {
      id: 50,
      title: "Savolla",
      pictureDir: "/pictures/sy/savolla.png",
      chosen: false,
    },
  ],
};

export default data;
